HTTP/1.1 503 OK
Content-Type: text/html; charset=UTF-8

<html>
<head>
<title>Ow! -- reddit.com</title>
</head>
<body style="text-align: center">

<img src="http://sp.reddit.com/heavy-mallet.gif">
<br style="clear: both"/>
<div style="margin: auto; display: inline-block">

<h2 style="color: red; font-size: 200%;">
reddit is under heavy load right now, sorry.  Try again in a few minutes.
</h2>
</body>
</html>
