HTTP/1.1 504 OK
Content-Type: text/html; charset=UTF-8

<html>
<head>
<title>Ow! -- reddit.com</title>
</head>
<body style="text-align: center">

<img src="http://sp.reddit.com/heavy-mallet.gif">
<br style="clear: both"/>
<div style="margin: auto; display: inline-block">

<h2 style="color: red; font-size: 200%;">
Your request took too long for our servers, so we had to cut it off.  Try again and hopefully it will be fast enough this time.
</h2>
</body>
</html>
